version: '3.7'

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - image_service
      - logging_service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  user_service:
    build:
      context: ./services/user_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  image_service:
    build:
      context: ./services/image_service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  logging_service:
    build:
      context: ./services/logging_service
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: black_and_white_filter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
